import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { RecipeProvider } from "./context/RecipeContext"; // Ensure this path is correct
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap everything (including Sidebar) in the Provider */}
        <Providers>
        <RecipeProvider>
          <Navbar />
          <main>
            {/* If DashboardSidebar is here, it will now correctly access the context */}
            {children}
          </main>
          <Footer />
        </RecipeProvider>
        </Providers>
      </body>
    </html>
  );
}

